# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/custom_download_strategy"
class Gauth < Formula
  desc "高途 all-in-one 授权工具：用 CAS 登录态换取业务站点的会话 cookie"
  homepage "https://github.com/amzyang/gauth"
  version "0.1.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/amzyang/gauth/releases/download/v0.1.4/gauth_0.1.4_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "7c2c71be3fdc5bc16da23608ef478ba857e66f9a1d19489a601724d55d50042d"

      define_method(:install) do
        bin.install "gauth"
        generate_completions_from_executable(bin/"gauth", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/amzyang/gauth/releases/download/v0.1.4/gauth_0.1.4_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "2c3e590da20aca067c73d35abb3330de71ec3a5aa67ca852a258180042483c32"

      define_method(:install) do
        bin.install "gauth"
        generate_completions_from_executable(bin/"gauth", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/amzyang/gauth/releases/download/v0.1.4/gauth_0.1.4_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "ab05584d973386b79b745b57ea99dd77ca5da9b742c853cca49bef1f75b1e2c9"
      define_method(:install) do
        bin.install "gauth"
        generate_completions_from_executable(bin/"gauth", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/amzyang/gauth/releases/download/v0.1.4/gauth_0.1.4_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "ba08a0485ece72492ee4478ebe6680a06bf29da9fe11c350491c71cd45597a37"
      define_method(:install) do
        bin.install "gauth"
        generate_completions_from_executable(bin/"gauth", "completion")
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gauth --version")
    system "#{bin}/gauth", "preset", "list"
  end
end
