# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/custom_download_strategy"
class Gloop < Formula
  desc "CozeLoop 私有化部署命令行工具"
  homepage "https://github.com/amzyang/gloop"
  version "0.1.2"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/amzyang/gloop/releases/download/v0.1.2/gloop_0.1.2_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "78e628958619a42c3eda6d296cceafccb93dab7284fce01fa8cb27488ac0b5a0"

      define_method(:install) do
        bin.install "gloop"
        generate_completions_from_executable(bin/"gloop", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/amzyang/gloop/releases/download/v0.1.2/gloop_0.1.2_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "5405331b529f80f888649345bee6155b93fda4a051b6e5dbdc40159d599d3279"

      define_method(:install) do
        bin.install "gloop"
        generate_completions_from_executable(bin/"gloop", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/amzyang/gloop/releases/download/v0.1.2/gloop_0.1.2_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "f61ba063f30d8380de738e6aa5c2694c6507215993aa80a67499818c0b20ef99"
      define_method(:install) do
        bin.install "gloop"
        generate_completions_from_executable(bin/"gloop", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/amzyang/gloop/releases/download/v0.1.2/gloop_0.1.2_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "d2ae65680f37ff9a20fec6539f29832de7464d8bca0a54fa427852d9c1bc4512"
      define_method(:install) do
        bin.install "gloop"
        generate_completions_from_executable(bin/"gloop", "completion")
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gloop --version")
    system "#{bin}/gloop", "--help"
  end
end
