# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/custom_download_strategy"
class Gloop < Formula
  desc "CozeLoop 私有化部署命令行工具"
  homepage "https://github.com/amzyang/gloop"
  version "0.1.3"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/amzyang/gloop/releases/download/v0.1.3/gloop_0.1.3_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "fa0d0ba602d4ea5e9f29700793eb8847d3d0fd4409ac0f188278fd30fa6d9675"

      define_method(:install) do
        bin.install "gloop"
        generate_completions_from_executable(bin/"gloop", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/amzyang/gloop/releases/download/v0.1.3/gloop_0.1.3_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "7fccf897492fdd4ca67b1711792eb505edcf576d4c5933485de99fc3a7f8524b"

      define_method(:install) do
        bin.install "gloop"
        generate_completions_from_executable(bin/"gloop", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/amzyang/gloop/releases/download/v0.1.3/gloop_0.1.3_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "5747c1f788aef8a30aa70deae4cc25422cbccb36c981df8c11a2fb2e40680bc0"
      define_method(:install) do
        bin.install "gloop"
        generate_completions_from_executable(bin/"gloop", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/amzyang/gloop/releases/download/v0.1.3/gloop_0.1.3_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "e392c364a8dba6b1923b67b4306f578dfedfc48c5de3acd405dd2ce197374d12"
      define_method(:install) do
        bin.install "gloop"
        generate_completions_from_executable(bin/"gloop", "completion")
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gloop --version")
    system "#{bin}/gloop", "--help"
  end
end
