# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/custom_download_strategy"
class Gloop < Formula
  desc "CozeLoop 私有化部署命令行工具"
  homepage "https://github.com/amzyang/gloop"
  version "0.1.6"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/amzyang/gloop/releases/download/v0.1.6/gloop_0.1.6_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "fafb0331f562f6eca529234358d4693b460142f6405336d02512c74e40866e86"

      define_method(:install) do
        bin.install "gloop"
        generate_completions_from_executable(bin/"gloop", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/amzyang/gloop/releases/download/v0.1.6/gloop_0.1.6_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "af82c118277302f7f45d2b8e795a01af33d3c0250df758c9c62ffcc0ff10788d"

      define_method(:install) do
        bin.install "gloop"
        generate_completions_from_executable(bin/"gloop", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/amzyang/gloop/releases/download/v0.1.6/gloop_0.1.6_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "a4f7d12a415f73922ffdd4d75fb3084a0720eeecd65a58761fa1ff714f9ee0d6"
      define_method(:install) do
        bin.install "gloop"
        generate_completions_from_executable(bin/"gloop", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/amzyang/gloop/releases/download/v0.1.6/gloop_0.1.6_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "b447dbe234aecaf8b2f4dabd4bbcd6cb03c55c62e85c6fe616fd42c6f14a76b1"
      define_method(:install) do
        bin.install "gloop"
        generate_completions_from_executable(bin/"gloop", "completion")
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gloop --version")
    system "#{bin}/gloop", "--help"
  end
end
