# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/custom_download_strategy"
class Gredis < Formula
  desc "公司 Redis Web 平台查询接口的命令行网关"
  homepage "https://github.com/amzyang/gredis"
  version "0.1.0"
  license "Proprietary"

  depends_on "iredis"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/amzyang/gredis/releases/download/v0.1.0/gredis_0.1.0_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "d93575f84100df18bc49cfc29b50ef74b62fe035931e62e3bd8e77b19929debe"

      define_method(:install) do
        bin.install "gredis"
        generate_completions_from_executable(bin/"gredis", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/amzyang/gredis/releases/download/v0.1.0/gredis_0.1.0_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "c3d2b5181b3eb3036af3d55d87fa320810f8fe34d6a5b2baa2332ae43a0b014e"

      define_method(:install) do
        bin.install "gredis"
        generate_completions_from_executable(bin/"gredis", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/amzyang/gredis/releases/download/v0.1.0/gredis_0.1.0_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "becf8523164567acc86d23df85f2d238db7082b573c90467e3117849e4bb14cd"
      define_method(:install) do
        bin.install "gredis"
        generate_completions_from_executable(bin/"gredis", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/amzyang/gredis/releases/download/v0.1.0/gredis_0.1.0_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "2fe0ee1944b3d64b398237c98037adea0435396872c233ada0f9e3c2441b36ab"
      define_method(:install) do
        bin.install "gredis"
        generate_completions_from_executable(bin/"gredis", "completion")
      end
    end
  end

  service do
    run [opt_bin/"gredis", "server"]
    keep_alive crashed: true
    log_path var/"log/gredis-server.log"
    error_log_path var/"log/gredis-server.log"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gredis --version")
    system "#{bin}/gredis", "--help"
  end
end
