# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/custom_download_strategy"
class Gredis < Formula
  desc "公司 Redis Web 平台查询接口的命令行网关"
  homepage "https://github.com/amzyang/gredis"
  version "0.9.0"
  license "Proprietary"

  depends_on "amzyang/tap/iredis"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/amzyang/gredis/releases/download/v0.9.0/gredis_0.9.0_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "941b5437dd5aecac2ac674e0a0f631333afb7d9971cac5a0fc2a2918e3294d4c"

      define_method(:install) do
        bin.install "gredis"
        generate_completions_from_executable(bin/"gredis", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/amzyang/gredis/releases/download/v0.9.0/gredis_0.9.0_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "7f1e5fa3ca2b75d42e3d60d8042f2acf0dcf305ff80825facbd4f5916c475363"

      define_method(:install) do
        bin.install "gredis"
        generate_completions_from_executable(bin/"gredis", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/amzyang/gredis/releases/download/v0.9.0/gredis_0.9.0_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "38dda3a25215b73ec00e4cda43b0c49c2640b2e32f0438116524267cbb87ec08"
      define_method(:install) do
        bin.install "gredis"
        generate_completions_from_executable(bin/"gredis", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/amzyang/gredis/releases/download/v0.9.0/gredis_0.9.0_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "7ddc35ab3e8b83bbe3d858f54370ec9965e653e51055cabcd68acee1a45eae7a"
      define_method(:install) do
        bin.install "gredis"
        generate_completions_from_executable(bin/"gredis", "completion")
      end
    end
  end

  service do
    run [opt_bin/"gredis", "server"]
    keep_alive crashed: true
    log_path var/"log/gredis-server.log"
    error_log_path var/"log/gredis-server.log"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gredis --version")
    system "#{bin}/gredis", "--help"
  end
end
