# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/custom_download_strategy"
class Gredis < Formula
  desc "公司 Redis Web 平台查询接口的命令行网关"
  homepage "https://github.com/amzyang/gredis"
  version "0.10.0"
  license "Proprietary"

  depends_on "amzyang/tap/iredis"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/amzyang/gredis/releases/download/v0.10.0/gredis_0.10.0_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "9a026d801aadba37a0a59b63c9d0c151530ae6bb4b7c4e02164d1dbbbbaa2542"

      define_method(:install) do
        bin.install "gredis"
        generate_completions_from_executable(bin/"gredis", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/amzyang/gredis/releases/download/v0.10.0/gredis_0.10.0_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "3626ad2e6d8e232020410b1caea3badbb6c51685d39489c6853d9601cd0a4fb4"

      define_method(:install) do
        bin.install "gredis"
        generate_completions_from_executable(bin/"gredis", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/amzyang/gredis/releases/download/v0.10.0/gredis_0.10.0_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "757702db564d2b9093d8cd6daaa5c9d45eb00168c76063b3a5a26003c4e6c4a2"
      define_method(:install) do
        bin.install "gredis"
        generate_completions_from_executable(bin/"gredis", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/amzyang/gredis/releases/download/v0.10.0/gredis_0.10.0_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "9eafcdff1150051a979f0bd4548dc3d0d8eb6da21241a2e43d77d3fdcea95b2a"
      define_method(:install) do
        bin.install "gredis"
        generate_completions_from_executable(bin/"gredis", "completion")
      end
    end
  end

  service do
    run [opt_bin/"gredis", "server"]
    keep_alive crashed: true
    log_path var/"log/gredis-server.log"
    error_log_path var/"log/gredis-server.log"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gredis --version")
    system "#{bin}/gredis", "--help"
  end
end
