# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/custom_download_strategy"
class Gsql < Formula
  desc "公司 SRE 平台网页版只读 SQL 接口的命令行网关"
  homepage "https://github.com/amzyang/gsql"
  version "0.3.8"
  license "Proprietary"

  depends_on "mycli"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/amzyang/gsql/releases/download/v0.3.8/gsql_0.3.8_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "85af9fc23c58d46c502524d2bc8e63fe0084a5a136bb313961ee6c3f56e4d46c"

      define_method(:install) do
        bin.install "gsql"
        generate_completions_from_executable(bin/"gsql", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/amzyang/gsql/releases/download/v0.3.8/gsql_0.3.8_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "8d9e68cfe1830603db7332278b4b4a1262502ebf66a632090382ce8ccfec400d"

      define_method(:install) do
        bin.install "gsql"
        generate_completions_from_executable(bin/"gsql", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/amzyang/gsql/releases/download/v0.3.8/gsql_0.3.8_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "5132545aa09ec61311664bf9822c57d0dee5bcc33c20c0da18d49a4e37466bbd"
      define_method(:install) do
        bin.install "gsql"
        generate_completions_from_executable(bin/"gsql", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/amzyang/gsql/releases/download/v0.3.8/gsql_0.3.8_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "e663e9d1a4a2bfd378d0f4b945785611a39e9d6279fd85829193f01c35bee3a0"
      define_method(:install) do
        bin.install "gsql"
        generate_completions_from_executable(bin/"gsql", "completion")
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gsql --version")
    system "#{bin}/gsql", "--help"
  end
end
