# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K9s < Formula
  desc "Kubernetes CLI To Manage Your Clusters In Style! (amzyang fork)"
  homepage "https://github.com/amzyang/k9s"
  version "0.51.0-amz.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/amzyang/k9s/releases/download/v0.51.0-amz.1/k9s_0.51.0-amz.1_darwin_amd64.tar.gz"
      sha256 "704532a6b5d8c6d1add066a64fb135aacb8407f863469c3cb09df7dedfb4da1c"

      define_method(:install) do
        bin.install "k9s"
        generate_completions_from_executable(bin/"k9s", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/amzyang/k9s/releases/download/v0.51.0-amz.1/k9s_0.51.0-amz.1_darwin_arm64.tar.gz"
      sha256 "4bab625e8c6712882cc78617c4a38fd14cb7bfa3d038284bb684b983bbc02bc0"

      define_method(:install) do
        bin.install "k9s"
        generate_completions_from_executable(bin/"k9s", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/amzyang/k9s/releases/download/v0.51.0-amz.1/k9s_0.51.0-amz.1_linux_amd64.tar.gz"
      sha256 "ef00e11a50b7d37950f546fdc729e0172eacfa1c0b5423c48d9e5a1728e4a870"
      define_method(:install) do
        bin.install "k9s"
        generate_completions_from_executable(bin/"k9s", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/amzyang/k9s/releases/download/v0.51.0-amz.1/k9s_0.51.0-amz.1_linux_arm64.tar.gz"
      sha256 "9accb372d8adc78a4ca790f1b89680fc66304ba82ca561559afeca60fdd4417a"
      define_method(:install) do
        bin.install "k9s"
        generate_completions_from_executable(bin/"k9s", "completion")
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/k9s version -s")
  end
end
