# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Larkdown < Formula
  desc "飞书文档与 Markdown 双向转换 CLI（下载/上传/增量更新）"
  homepage "https://github.com/amzyang/larkdown"
  version "3.26.1"
  license "MIT"

  depends_on "imagemagick"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/amzyang/larkdown/releases/download/v3.26.1/larkdown_3.26.1_darwin_amd64.tar.gz"
      sha256 "b63dad0d1ff2b10c6cd1a884bb1043cad3e803b057e868bb3e757e99de777ca5"

      define_method(:install) do
        bin.install "larkdown"
        generate_completions_from_executable(bin/"larkdown", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/amzyang/larkdown/releases/download/v3.26.1/larkdown_3.26.1_darwin_arm64.tar.gz"
      sha256 "29ece234a4b464126938d0af666ecec7e5608f4a7edcdcab8bcc04eccc078821"

      define_method(:install) do
        bin.install "larkdown"
        generate_completions_from_executable(bin/"larkdown", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/amzyang/larkdown/releases/download/v3.26.1/larkdown_3.26.1_linux_amd64.tar.gz"
      sha256 "56cfa30e8d4e44bad73a423217776f51bd995e6c32406b0b9a4ddf36096648aa"
      define_method(:install) do
        bin.install "larkdown"
        generate_completions_from_executable(bin/"larkdown", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/amzyang/larkdown/releases/download/v3.26.1/larkdown_3.26.1_linux_arm64.tar.gz"
      sha256 "a488c1dfce3b70be85f15452012ed2257e962c18a719a5ed45e8c02c8967a3f8"
      define_method(:install) do
        bin.install "larkdown"
        generate_completions_from_executable(bin/"larkdown", "completion")
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/larkdown --version")
    system "#{bin}/larkdown", "--help"
  end
end
