# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Larkim < Formula
  desc "Feishu/Lark IM synced to local SQLite: background daemon, CLI and TUI"
  homepage "https://github.com/amzyang/larkim"
  version "0.22.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/amzyang/larkim/releases/download/v0.22.1/larkim_0.22.1_darwin_amd64.tar.gz"
      sha256 "f0dd97407133c6160fdc546026a92ce70affdd4aa3e6a5d069a877fae7b8127c"

      define_method(:install) do
        bin.install "larkim"
        generate_completions_from_executable(bin/"larkim", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/amzyang/larkim/releases/download/v0.22.1/larkim_0.22.1_darwin_arm64.tar.gz"
      sha256 "6fd82c0c16ce00ea05889629730f4efcb3552587d5d8a7b8ff43b8e1d1fc6b06"

      define_method(:install) do
        bin.install "larkim"
        generate_completions_from_executable(bin/"larkim", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/amzyang/larkim/releases/download/v0.22.1/larkim_0.22.1_linux_amd64.tar.gz"
      sha256 "531d37934ad5da3a693a2cb288566c939d9033c71300eb6c9cd8eded5e940267"
      define_method(:install) do
        bin.install "larkim"
        generate_completions_from_executable(bin/"larkim", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/amzyang/larkim/releases/download/v0.22.1/larkim_0.22.1_linux_arm64.tar.gz"
      sha256 "76c921400a15e86e27a6168a22c589d5cff4c8ecfe33a10dcb1a6eadc54a8351"
      define_method(:install) do
        bin.install "larkim"
        generate_completions_from_executable(bin/"larkim", "completion")
      end
    end
  end

  def caveats
    <<~EOS
      larkim drives the official lark-cli for authentication and API access:
        npm install -g @larksuite/cli
        lark-cli auth login --domain im,contact
      Then start the sync service:
        brew services start larkim
    EOS
  end

  service do
    run [opt_bin/"larkim", "daemon", "run"]
    keep_alive true
    log_path var/"log/larkim.log"
    error_log_path var/"log/larkim.log"
  end

  test do
    system "#{bin}/larkim", "--version"
    assert_match "larkim", shell_output("#{bin}/larkim completion fish")
  end
end
