# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Larkim < Formula
  desc "Feishu/Lark IM synced to local SQLite: background daemon, CLI and TUI"
  homepage "https://github.com/amzyang/larkim"
  version "0.21.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/amzyang/larkim/releases/download/v0.21.4/larkim_0.21.4_darwin_amd64.tar.gz"
      sha256 "3359f8c675601554a2f71cec9583f1b5cae29f62d5ae5cbf3be2e35682467b9b"

      define_method(:install) do
        bin.install "larkim"
        generate_completions_from_executable(bin/"larkim", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/amzyang/larkim/releases/download/v0.21.4/larkim_0.21.4_darwin_arm64.tar.gz"
      sha256 "e6b0e06ca92ef2b0c9e5680371525039e02cc91c34ff3e349bb5215568329198"

      define_method(:install) do
        bin.install "larkim"
        generate_completions_from_executable(bin/"larkim", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/amzyang/larkim/releases/download/v0.21.4/larkim_0.21.4_linux_amd64.tar.gz"
      sha256 "60fc4e0d83a6b781e3d17ed7601f1333f2f2b8f9b65fa17c6542102f7ec75e56"
      define_method(:install) do
        bin.install "larkim"
        generate_completions_from_executable(bin/"larkim", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/amzyang/larkim/releases/download/v0.21.4/larkim_0.21.4_linux_arm64.tar.gz"
      sha256 "2df4ea5fa19f04b7b63cda00a7eb660b24d0fc50dabe2fc221e940ce8c1e346c"
      define_method(:install) do
        bin.install "larkim"
        generate_completions_from_executable(bin/"larkim", "completion")
      end
    end
  end

  def caveats
    <<~EOS
      larkim drives the official lark-cli for authentication and API access:
        npm install -g @larksuite/cli
        lark-cli auth login --domain im,contact
      Then start the sync service:
        brew services start larkim
    EOS
  end

  service do
    run [opt_bin/"larkim", "daemon", "run"]
    keep_alive true
    log_path var/"log/larkim.log"
    error_log_path var/"log/larkim.log"
  end

  test do
    system "#{bin}/larkim", "--version"
    assert_match "larkim", shell_output("#{bin}/larkim completion fish")
  end
end
