# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Larkim < Formula
  desc "Feishu/Lark IM synced to local SQLite: background daemon, CLI and TUI"
  homepage "https://github.com/amzyang/larkim"
  version "0.21.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/amzyang/larkim/releases/download/v0.21.11/larkim_0.21.11_darwin_amd64.tar.gz"
      sha256 "38a810a71163ebec6646ff7e6008cbcb9c42f62c7ea2a04a1ee639b20ac29b63"

      define_method(:install) do
        bin.install "larkim"
        generate_completions_from_executable(bin/"larkim", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/amzyang/larkim/releases/download/v0.21.11/larkim_0.21.11_darwin_arm64.tar.gz"
      sha256 "164f75109ab29f0a458f9a35eabc584de010d8d04f27695722d6de104318b7fa"

      define_method(:install) do
        bin.install "larkim"
        generate_completions_from_executable(bin/"larkim", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/amzyang/larkim/releases/download/v0.21.11/larkim_0.21.11_linux_amd64.tar.gz"
      sha256 "447c4fc2d002fe79fb68886eee0fd730c5b1a31f025386526d7133a0f7daa33a"
      define_method(:install) do
        bin.install "larkim"
        generate_completions_from_executable(bin/"larkim", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/amzyang/larkim/releases/download/v0.21.11/larkim_0.21.11_linux_arm64.tar.gz"
      sha256 "52b06434e894b1e5e2b069f1e9d6c403558529eafe5de0358d75eef1216e4d6c"
      define_method(:install) do
        bin.install "larkim"
        generate_completions_from_executable(bin/"larkim", "completion")
      end
    end
  end

  def caveats
    <<~EOS
      larkim drives the official lark-cli for authentication and API access:
        npm install -g @larksuite/cli
        lark-cli auth login --domain im,contact
      Then start the sync service:
        brew services start larkim
    EOS
  end

  service do
    run [opt_bin/"larkim", "daemon", "run"]
    keep_alive true
    log_path var/"log/larkim.log"
    error_log_path var/"log/larkim.log"
  end

  test do
    system "#{bin}/larkim", "--version"
    assert_match "larkim", shell_output("#{bin}/larkim completion fish")
  end
end
