# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Room < Formula
  desc "Meeting room booking automation CLI for Feishu (Lark)"
  homepage "https://github.com/amzyang/room"
  version "0.6.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/amzyang/room/releases/download/v0.6.4/room_0.6.4_darwin_amd64.tar.gz"
      sha256 "6dc8d9da0db3377cc81fc77a21b1f5d5e2432352f05fd7520718ef708810fe15"

      define_method(:install) do
        bin.install "room"
        generate_completions_from_executable(bin/"room", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/amzyang/room/releases/download/v0.6.4/room_0.6.4_darwin_arm64.tar.gz"
      sha256 "f9c3fe51542255fed257d9a57683b47330e6cae8156b7e1701fb8cc966b2fea5"

      define_method(:install) do
        bin.install "room"
        generate_completions_from_executable(bin/"room", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/amzyang/room/releases/download/v0.6.4/room_0.6.4_linux_amd64.tar.gz"
      sha256 "cd15e0ea3eafd15273303cc0e4cc79a6a63e9c749c7a4ab4815d605cb3b1797f"
      define_method(:install) do
        bin.install "room"
        generate_completions_from_executable(bin/"room", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/amzyang/room/releases/download/v0.6.4/room_0.6.4_linux_arm64.tar.gz"
      sha256 "ac55eb0211690be9611bd58244fa85741cc742470e06fb3fbdcfae8ae6f9d7bb"
      define_method(:install) do
        bin.install "room"
        generate_completions_from_executable(bin/"room", "completion")
      end
    end
  end

  service do
    run [opt_bin/"room", "keepalive"]
    run_type :interval
    interval 172800
    log_path var/"log/room-keepalive.log"
    error_log_path var/"log/room-keepalive.log"
  end

  test do
    system "#{bin}/room --version"
  end
end
