# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Room < Formula
  desc "Meeting room booking automation CLI for Feishu (Lark)"
  homepage "https://github.com/amzyang/room"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/amzyang/room/releases/download/v0.4.0/room_0.4.0_darwin_amd64.tar.gz"
      sha256 "fc652e6d25fceb058ccd5f7486e21e45f544958de235f52a1c8c4c105fc8c597"

      define_method(:install) do
        bin.install "room"
        generate_completions_from_executable(bin/"room", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/amzyang/room/releases/download/v0.4.0/room_0.4.0_darwin_arm64.tar.gz"
      sha256 "cec1331b63a8215d834fdf56e1edd0a25bd91621fb4f3ce43d59633acb3198c8"

      define_method(:install) do
        bin.install "room"
        generate_completions_from_executable(bin/"room", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/amzyang/room/releases/download/v0.4.0/room_0.4.0_linux_amd64.tar.gz"
      sha256 "957de2f3a0a76767f5dc0a8d30331992ff403f84cd0c6a13519aa954b0b62e7d"
      define_method(:install) do
        bin.install "room"
        generate_completions_from_executable(bin/"room", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/amzyang/room/releases/download/v0.4.0/room_0.4.0_linux_arm64.tar.gz"
      sha256 "b39792637ae7ccd6cd0f261716c3bb362fc189619e54d6942a54ac5f3cae1f2e"
      define_method(:install) do
        bin.install "room"
        generate_completions_from_executable(bin/"room", "completion")
      end
    end
  end

  test do
    system "#{bin}/room --version"
  end
end
