# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/custom_download_strategy"
class Zcli < Formula
  desc "轻舟研发效能平台 TUI/CLI"
  homepage "https://github.com/amzyang/zcli"
  version "0.1.167"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/amzyang/zcli/releases/download/v0.1.167/zcli_0.1.167_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "77152346d924731e14b9c9a281c29f08db7503271648dceaa04c78ce584e2679"

      define_method(:install) do
        bin.install "zcli"
        generate_completions_from_executable(bin/"zcli", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/amzyang/zcli/releases/download/v0.1.167/zcli_0.1.167_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "a91d982a502a05f540687ff45ca0335d471a255e85a95960dd49520d38bad627"

      define_method(:install) do
        bin.install "zcli"
        generate_completions_from_executable(bin/"zcli", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/amzyang/zcli/releases/download/v0.1.167/zcli_0.1.167_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "d021d1f38e11dc750df1fa54772934d69b42e506e22fbb776bfd0c2d782944c0"
      define_method(:install) do
        bin.install "zcli"
        generate_completions_from_executable(bin/"zcli", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/amzyang/zcli/releases/download/v0.1.167/zcli_0.1.167_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "63c63f487f029485286e1a869882c0a23e04062a0164ac90cfbf89a0c2a3e30f"
      define_method(:install) do
        bin.install "zcli"
        generate_completions_from_executable(bin/"zcli", "completion")
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/zcli --version")
    system "#{bin}/zcli", "--help"
  end
end
