# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/custom_download_strategy"
class Zcli < Formula
  desc "轻舟研发效能平台 TUI/CLI"
  homepage "https://github.com/amzyang/zcli"
  version "0.1.63"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/amzyang/zcli/releases/download/v0.1.63/zcli_0.1.63_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "a866708884147d67dd35f6b5a7413b2833b87c0d6f1f181361ab92a9a272ecb5"

      define_method(:install) do
        bin.install "zcli"
        generate_completions_from_executable(bin/"zcli", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/amzyang/zcli/releases/download/v0.1.63/zcli_0.1.63_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "ffe7afc6e98299918d38a54ec7d90717f3d46f64c71b5e83d2d2feaf77f4bfe8"

      define_method(:install) do
        bin.install "zcli"
        generate_completions_from_executable(bin/"zcli", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/amzyang/zcli/releases/download/v0.1.63/zcli_0.1.63_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "f2a785d37b50dd943aebeda5ed5320b87d7154d7e5f9959f1c12534b5d79529f"
      define_method(:install) do
        bin.install "zcli"
        generate_completions_from_executable(bin/"zcli", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/amzyang/zcli/releases/download/v0.1.63/zcli_0.1.63_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "ca6e87f0cb9f681f62a13d06c48619dc4cf589d6eec443375924fc86b73ba91b"
      define_method(:install) do
        bin.install "zcli"
        generate_completions_from_executable(bin/"zcli", "completion")
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/zcli --version")
    system "#{bin}/zcli", "--help"
  end
end
